/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author jhony
 */
public class PantallaMenu extends javax.swing.JFrame {

    /**
     * Creates new form PantallaMenu
     */
    public PantallaMenu() {
        initComponents();
        TransparenciaBtn();
    }
    public void TransparenciaBtn(){//funcion para poner el boton sin fondo
        btn_jugar.setOpaque(false);
        btn_jugar.setContentAreaFilled(false);
        btn_jugar.setBorderPainted(false);
}

    public PantallaMenu(JButton btn_jugar, JLabel jLabel1, JLabel jLabel3, JPanel jPanel1, JLabel label, JTextField txt1) throws HeadlessException {
        this.btn_jugar = btn_jugar;
        this.jLabel1 = jLabel1;
  
        this.jPanel1 = jPanel1;
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_jugar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(800, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_jugar.setForeground(new java.awt.Color(255, 255, 255));
        btn_jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Images/jugarbozetobtn.png"))); // NOI18N
        btn_jugar.setBorderPainted(false);
        btn_jugar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jugarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 410, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Images/R.jpeg"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 820));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jugarActionPerformed
        //TableroBattle abrirTablero = new TableroBattle();
        //abrirTablero();
        //abrirTablero.setVisible(true);
       TableroBattle.Tablero();
        this.dispose();
       //this.setVisible(false);
    }//GEN-LAST:event_btn_jugarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_jugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
